version: '3.4'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

services:
  api:
    container_name: api_supermarket
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/node/app
    command: npm run start:dev
    hostname: app_supermarket
    environment:
      - HOST_DATABASE=192.168.55.1
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      default:
        ipv4_address: 192.168.55.3

  postgres:
    container_name: postgres_container
    image: postgres
    hostname: db_supermarket
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: supermarket
      PGDATA: /data/postgres
    volumes:
      - postgres_vol:/data/postgres
    ports:
      - "5444:5432"
    restart: unless-stopped

volumes:
  postgres_vol:
    driver: local

