version: '3.1'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: supermarket
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5444:5432"
    networks:
      - postgres
    restart: unless-stopped
  

networks:
  postgres:
    driver: bridge

volumes:
    postgres: