version: '3.7'

services:
  api:
    container_name: api_supermarket
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/node/app
    command: npm run start:dev
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    hostname: db_supermarket
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: supermarket
      PGDATA: /data/postgres
    volumes:
      - postgres_vol:/data/postgres
    ports:
      - "5444:5432"
    networks:
      - postgres
    restart: unless-stopped

volumes:
  postgres_vol:
    driver: local


networks:
  postgres:
    driver: bridge
